name: Code Quality Lints

on:
  push:
    branches: [main]
  pull_request:

env:
    RUST_BACKTRACE: 1
    CARGO_TERM_COLOR: always


jobs:
    check: 
        runs-on: macos-latest
        name: cargo check
        steps:
          - run: cargo check

    build:
        runs-on: macos-latest
        name: build code
        steps:
          - run: cargo build
          - run: cargo build --release

    format:
        runs-on: macos-latest
        name: check format
        steps:
          - run: cargo fmt --check
    
    # I think warnings are the right level here for now,
    # can do pedantic lints separately w/ pre-commit if I'd like
    clippy:
        runs-on: macos-latest
        name: run clippy
        steps:
          - run: cargo clippy --workspace --all-targets -- -D warnings

